// Generated by SandPiper(TM).
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


// For X injection on assignments, disableable using `define SP_PHYS.
`ifdef WHEN
   $warning("WHEN macro redefined.");
`endif
`ifdef SP_PHYS
   `define WHEN(valid_sig)
`else
   `define WHEN(valid_sig) !valid_sig ? 'x :
`endif





//
// Scope: |default
//

// For |default$lfsr.
logic [LFSR_WIDTH-1:0] DEFAULT_lfsr_a0;
logic [LFSR_WIDTH-1:0] DEFAULT_lfsr_a1;

// For |default$reset.
logic DEFAULT_reset_a0;



   //
   // Scope: |default
   //

      // Staging of $lfsr.
      always_ff @(posedge clk) DEFAULT_lfsr_a1[LFSR_WIDTH-1:0] <= DEFAULT_lfsr_a0[LFSR_WIDTH-1:0];



