// Generated by SandPiper(TM).
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$lfsr.
logic [LFSR_WIDTH-1:0] DEFAULT_lfsr_a0,
                       DEFAULT_lfsr_a1;

// For |default$reset.
logic DEFAULT_reset_a0;




   //
   // Scope: |default
   //

      // Staging of $lfsr.
      always_ff @(posedge clk) DEFAULT_lfsr_a1[LFSR_WIDTH-1:0] <= DEFAULT_lfsr_a0[LFSR_WIDTH-1:0];






//
// Debug Signals
//

   if (1) begin : DEBUG_SIGS


      //
      // Scope: |default
      //
      if (1) begin : \|default 
         logic [LFSR_WIDTH-1:0] \@0$lfsr ;
         assign \@0$lfsr = DEFAULT_lfsr_a0;
         logic  \@0$reset ;
         assign \@0$reset = DEFAULT_reset_a0;
      end


   end

