// Generated by SandPiper(TM).
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


`include "sandpiper_gen.vh"





//
// Signals declared top-level.
//

// For |default$lfsr.
wire [LFSR_WIDTH-1:0] DEFAULT_lfsr_a0;
reg  [LFSR_WIDTH-1:0] DEFAULT_lfsr_a1;

// For |default$reset.
wire DEFAULT_reset_a0;




   //
   // Scope: |default
   //
   generate if (1) begin : L1gen_DEFAULT
      // Staging of $lfsr.
      always @(posedge clk) DEFAULT_lfsr_a1[LFSR_WIDTH-1:0] <= DEFAULT_lfsr_a0[LFSR_WIDTH-1:0];

   end endgenerate




//
// Debug Signals
//

generate

   if (1) begin : DEBUG_SIGS


      //
      // Scope: |default
      //
      if (1) begin : \|default 
         wire [LFSR_WIDTH-1:0] \@0$lfsr ;
         assign \@0$lfsr = DEFAULT_lfsr_a0;
         wire  \@0$reset ;
         assign \@0$reset = DEFAULT_reset_a0;
      end


   end

endgenerate

